syntax = "proto3";

package jewelry.notification.v1;

option go_package = "github.com/JJIiSSH/jewelry-store/gen/notification/v1";

service NotificationService {
    rpc SendOrderNotification(OrderNotificationRequest) returns (OrderNotificationResponse);
}

message OrderNotificationRequest{
    string order_id = 1;
    string customer_email = 2;
    string contact_phone = 3;
    string customer_name = 4; 
    string shipping_address = 5; 
    string comment = 6; 
    double total = 7; 
    repeated OrderItem items = 8;
}

message OrderItem{
    string title = 1;
    double price = 2;
    int32 quantity = 3;
}

message OrderNotificationResponse{
    string notification_id = 1; 
    bool success = 2; 
    string message = 3;
}
 

